### ISSUE TITLE
Had to make a manual Pull Request

### ISSUE THREAD

**Issue by vpul** [learn-co-curriculum/javascript-logging-lab#23]
Saw the following error in my IDE:

```
Submitting lesson...                                                                                                          
/usr/local/rvm/gems/ruby-2.2.3/gems/learn-submit-1.2.0/lib/learn_submit/submission/git_interactor.rb:33:in `repo_name': undefi
ned method `[]' for nil:NilClass (NoMethodError)                                                                              
        from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-submit-1.2.0/lib/learn_submit/submission.rb:114:in `submit!'           
        from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-submit-1.2.0/lib/learn_submit/submission.rb:28:in `create'             
        from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-submit-1.2.0/lib/learn_submit/submission.rb:8:in `create'              
        from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-submit-1.2.0/bin/learn-submit:15:in `<top (required)>'                 
        from /usr/local/rvm/gems/ruby-2.2.3/bin/learn-submit:23:in `load'                                                     
        from /usr/local/rvm/gems/ruby-2.2.3/bin/learn-submit:23:in `<main>'                                                   
        from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'                                            
        from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>' 
```

Using Ubuntu 16.04
Learn gem 3.6.0
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

**Comment by AnnJohn** [comment]
hi @vipul this looks like a technical, product problem. If this is still a problem in other labs, could you please use Ask a Question and someone from our team will help you out right away. thanks!
